url: https://sharanjhangiani.com
title: Sharan Jhangiani
description: Sharan Jhangiani is a student at the University of Washington studying Data Science and Computational Finance at the University of Washington. He like thinking and talking about cities, innovative business models, and NLP research.
nav-links:
  - name: About
    url: /
  - name: Some (Un)Organized Thoughts
    url: /thoughts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true # automatically set is_post=true for all posts
permalink: /:title
baseurl: /sharanjhangiani.com
sass:
  style: compressed